name: MunchyMax
main: me.varmetek.munchymc.MunchyMax
version: 1.0.0
description: A MunchyPrison plugin made by Varmetek
authors:
  - Varmetek
depend: [ProtocolLib, PermissionsEx, Vault, WorldEdit, WorldGuard]
commands: